infer_dataset:
  - "/home/ssd_dir/flight_airsim_image/sequence8"

csv_name: "data_list.csv"

radian_weights_top_directory: "/home/ssd_dir/sequence_attitude_estimator_log/ViViT/train_log_2022_0729_best/"
radian_weights_file_name: "weights.pth"

degree_weights_top_directory: "/home/ssd_dir/sequence_attitude_estimator_log/ViViT/train_log_2022_0729_best/"
degree_weights_file_name: "weights.pth"

infer_log_top_directory: "/home/ssd_dir/sequence_attitude_estimator_log/ViViT/train_log_2022_0729_best/"
radian_infer_log_file_name: "frame_infer_relust_radian.csv"
degree_infer_log_file_name: "frame_infer_relust_degree.csv"

resize: 224
mean_element: 0.5
std_element: 0.5